apiVersion: v1
kind: Pod
metadata:
  namespace: build
spec:
  containers:
    - name: jnlp
      image: pi4k8s/inbound-agent:4.3
      env:
      - name: CONTAINER_ENV_VAR
        value: jnlp
    - name: docker
      image: docker:19.03
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run
    - name: docker-daemon
      image: docker:19.03-dind
      securityContext:
        privileged: true
      volumeMounts:
      - name: docker-socket
        mountPath: /var/run
  volumes:
    - name: docker-socket
      emptyDir: {}